.PHONY: all
all:
	make -C ex1 &
	make -C ex2 &
	make -C ex3 &
	make -C ex4 &
	make -C ex5 &
	make -C ex6 &
	jupyter notebook

.PHONY: clean
clean:
	make -C ex1 clean
	make -C ex2 clean 
	make -C ex3 clean 
	make -C ex4 clean 
	make -C ex5 clean 
	make -C ex6 clean 

